### ISSUE TITLE
Cant see gang blips

### ISSUE THREAD

**Issue by PlavnikHacks** [lucasvinbr/GTA5GangMod#18]
I installed the mod but other gangs blips dont show up so i dont know where territories are... any fix?

**Comment by lucasvinbr** [comment]
Hmmm, you've tried CTRL+N, right? If you did, maybe scripthookvdotnet.log could have info on why that isn't working as it should

**Comment by PlavnikHacks** [comment]
Lemme go test that. I have not.

**Comment by PlavnikHacks** [comment]
Okay just tested it, it works but it doesn't show the unused territories, just the ones that are claimed.

**Comment by lucasvinbr** [comment]
Hmmmm please try pressing CTRL+N more times then hehe; there are 3 "display modes" for the blips, "none", "5 closest zones" and "all zones". If some blips appeared if you've pressed it once, pressing it again should change the display mode to "all" and lots of blips should show up hehe. You can cycle between these display modes with CTRL+N
