### ISSUE TITLE
Can't See Territory Blips

### ISSUE THREAD

**Issue by PlavnikHacks** [lucasvinbr/GTA5GangMod#19]
When I pause and look at the map I cannot see the house shaped blips that usually say who owns that territory or if there isn't an owner then its grey.

**Comment by lucasvinbr** [comment]
Do the blips show up while the game isn't paused? If they don't please see the answer in the other issue https://github.com/lucasvinbr/GTA5GangMod/issues/18

**Comment by PlavnikHacks** [comment]
Okay thank you!
