### ISSUE TITLE
Help decreasing the amount of money earned

### ISSUE THREAD

**Issue by filipeeleal** [lucasvinbr/GTA5GangMod#21]
How i would decrease the amount of money earned by the turfs my gang own? 
Because i have 6 level 10 turfs and i earn almost 170.000 $ , i would like to decrease it
To make the mod more difficult to play .

Mano, você é o cara, me ajuda ai kk te stalkiei até aqui só pra pedir ajuda nisso, dá uma força ai é nois

**Comment by lucasvinbr** [comment]
hahaaah so, editing the ModOptions.xml file should be enough: try editing the msTimeBetweenTurfRewards, rewardMultiplierPerZone and baseRewardPerZoneOwned values (there's more info about them in the https://github.com/lucasvinbr/GTA5GangMod/wiki/ModOptions.xml-entries page).

If you reduce baseRewardPerZoneOwned and rewardMultiplierPerZone , you should get less money, but it should also affect the AI gangs. If you want them to keep getting as much money as before, you should increase the extraProfitForAIGangsFactor value.


kkkk tranquilo, se der mais problema pode mandar como issue aqui mesmo ou lá no discord (o link tá na página do mod no gta5mods)
