### ISSUE TITLE
Teammate Attacks

### ISSUE THREAD

**Issue by freakyneek** [lucasvinbr/GTA5GangMod#6]
I just wanted to clear up what some of the users are saying about a "bug" on the GTA5 Mods website. I was playing single player story mode again and noticed my teammates kill the NPC teammates (Not Trevor, Michael, or Franklin). One example is when Trevor and his friend are fighting the Aztecas after they meet the Chinese Triads and put them inside the freezer.

**Comment by lucasvinbr** [comment]
Hmm, I think I've noticed that happen too. I don't know how to fix it now, but I'll try to look into it

**Comment by freakyneek** [comment]
I'm assuming the AI is built into the game or script hook. If so, it would seem to be a very difficult task. If the AI can be programmed a bit, maybe have the bots do a name check for the NPC names in story mode?

**Comment by lucasvinbr** [comment]
Hmm, I couldn't find a way to get their names, but now there is an option, when selecting a ped to register, to make him/her an ally of your gang. That seems to work; I've tested it on that Aztecas mission and my members didn't get angry at Trevor's friend hehe.
