### ISSUE TITLE
Zix Edits

### ISSUE THREAD

**Issue by zixum** [lucasvinbr/GTA5GangMod#7]
[GTA5GangMod-zixrev1.zip](https://github.com/lucasvinbr/GTA5GangMod/files/518507/GTA5GangMod-zixrev1.zip)

Hey, I haven't got git set up on my windows machine - i use linux at work with some GUI nonsense, truth is i'm a real scrub when it comes to git and i couldn't find a way to message you. So here is my current WIP you requested.

It doesn't contain much:
- the controller mapping i started is available in ModCore onTick, will eventually extend it to include more options and probably want to wrap it in a config on/off if statement kind of deal.
  - played around with SpawnedDrivingGangMember abit, i use semi-realistic car handling mod and the speeds etc set in there were just crazy, and often could get me run over by my own gang :) For on foot i switched it to a static 50 on speed instead of the (7*distance) it was before and extended the radius to 25 from 10. With a larger radius they seem to be capable of decreasing their own speed for a safe stop.
  - In the "teleport" function in the same file, i tried to call EveryoneLeavesVehicle() but this broke the script, i imagine it then tries to do so some stuff after things have been set to null. So i used Hash.TASK_EVERYONE_LEAVE_VEHICLE instead and let your update function in that class handle the cleanup instead, which it seems to fine from testing. 

It means sometimes allies may not arrive if they get out of their car too far away or they'll be too much of a distance away to be useful. Ideally i'd like to do something tidier with this, perhaps if its a friendly vehicle send a message to the player saying backup couldn't get to them and attempt to respawn. If the player's not near any road access they should go figure. Either that or a toggle config option for "get out and walk if backup vehicle stuck"/"attempt respawn if backup vehicle stuck"/"attempt respawn if backup vehicle stuck x3 then get out and walk".

But it solves the whole enemies dropping in from behind and blasting you with a shotgun so i'm happy with it for now.

**Comment by zixum** [comment]
oops - i see why the TASK_EVERYONE_LEAVE_VEHICLE worked and not the function, its because everyoneleavesvehicle() is already outside the if statement below XD, so it would of ran twice hence causing problems, so really that whole if statement may aswell not exist, woops!

I'll try and do something about getting git set up and making more tidy edits if you'd like, back to work tomorrow though so no promises on a timeframe :P

**Comment by zixum** [comment]
[GTA5GangMod-zixrev4.zip](https://github.com/lucasvinbr/GTA5GangMod/files/518673/GTA5GangMod-zixrev4.zip)

My changes cleared up a bit, i wont be making any further changes for a few days and when/if i do/you want me to i'll make it properly over git.

Changes:
- Refactored some code into their own functions, just copied and dumped it if i needed to re-use parts of the code. Not sure if it'll be up to your tastes.
- Changed speed of gang spawned cars to a static value. Also changed radius they stop from you, up to 25 from 10 and the distance peds get out of the car respectively.
- Added new controls, using a controller can now aim and left (for backup), up (for current node info), right (for recruit target). This is configurable through xml option "joypadControls" default (true)
- Added new option "forceSpawnCars", just surrounded the teleport statement i was on about with an if config - default (true). But i like it off :P Until a more permanent solution is developed.

Know issues:
- The "up" controller seems inconsistent, sometimes the text just flashes randomly at the bottom of the screen but i notice the same with keyboard.
- Added last minute showMenu parameter to MenuScript.doCallBackup (new refactored function), not sure if its actually working or doing anything but it fixed the issue with the menu coming up on the controller. Alternatively it might be better to actually bind a couple of the menus themselves to the controller but i guess that's up to you to decide.
- I think there's some redundant code around (not mine), i commented on it where i found it on a couple of instances. Just some calls and stuff that i'm pretty sure aren't -actually- doing anything/taking effect and are being overridden by other code, but i didn't want to remove anything until i was sure - which i'm not yet.

**Comment by lucasvinbr** [comment]
Thanks a lot for the changes, but I think I'm going to take a closer look on them in the weekend only ahahaha

**Comment by zixum** [comment]
Not a problem

**Comment by lucasvinbr** [comment]
Finally got to adding the changes hahahah. Thanks a lot for contributing, and sorry for taking so long to update
